# 1. numpy tutorial

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3]) 
print(a)

[1 2 3]


In [6]:
b = np.array([[9,0,0,8],[5,4,5,6]]) 
print(b)

[[9 0 0 8]
 [5 4 5 6]]


In [7]:
#get dimension
a.ndim ##1
b.ndim ##2

2

In [8]:
#get shape
b.shape

(2, 4)

In [9]:
#get type
a.dtype

dtype('int64')