# 2.Accessing/changing specific elements, rows, columns etc.

In [2]:
import numpy as np

In [31]:
# 2d
a = np.array([
    [1,2,4,6,8,8],
              [2,4,6,4,7,5]
             ])
print(a)

[[1 2 4 6 8 8]
 [2 4 6 4 7 5]]


In [32]:
#3d
b = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                     [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])
print(b)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


# a)viewing values

In [26]:
#get specific element(r,C) 2d
a[1,3] #second row fourth column

np.int64(4)

In [ ]:
a[0,:] #all in first row 2d

In [24]:
a[:,2 ]# third digit in each row 2d

array([4, 6])

In [29]:
#getting a specific element (work outside in) in 3d
b[0,1,1] #first block, second row second column

np.int64(6)

In [30]:
b[1,2,1] #second block, third row, second column in 3d

np.int64(22)

## b)changing avalue

In [27]:
a[1, 4] = 12 #changed second row 5th column (7) to 12
print(a)

[[ 1  2  4  6  8  8]
 [ 2  4  6  4 12  5]]


In [36]:
#replacing value
b[:,1,:] # take all blocks, second row, all columns

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [37]:
b[:,2,:] # take all blocks, third row, all columns

array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])

In [39]:
b[[0,1],[1,0],:] #block 0 row 1, block 1 row 0, all columns

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])